apiVersion: v1
kind: Service
metadata:
  name: {{ include "graceful.fullname" . }}
  labels:
    {{- include "graceful.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9090
      protocol: TCP
      name: myweb
  selector:
    {{- include "graceful.selectorLabels" . | nindent 4 }}
